import type { ThemeSettings } from "./tokens";

export interface ThemePreset {
  name: string;
  description: string;
  settings: ThemeSettings;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: "Classic Parchment",
    description: "Warm browns and cream tones inspired by aged manuscripts",
    settings: {
      primaryColor: "#6b5344",
      secondaryColor: "#a89279",
      backgroundColor: "#faf6f1",
      textColor: "#2c2420",
      accentColor: "#8c7355",
      surfaceColor: "#f0ebe4",
      borderColor: "#d4c9bb",
      mutedColor: "#8a7e72",
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
  {
    name: "Midnight Chapel",
    description: "Deep charcoal with ivory and muted gold accents",
    settings: {
      primaryColor: "#c4a96a",
      secondaryColor: "#8a7d5a",
      backgroundColor: "#1c1b19",
      textColor: "#e8e4dc",
      accentColor: "#b89d5e",
      surfaceColor: "#2a2826",
      borderColor: "#3d3a36",
      mutedColor: "#8c877e",
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
  {
    name: "Stone Cathedral",
    description: "Cool greys and slate with burgundy accents",
    settings: {
      primaryColor: "#7a3b3b",
      secondaryColor: "#9c7a6e",
      backgroundColor: "#f4f2ef",
      textColor: "#2d2d2d",
      accentColor: "#8b4f4f",
      surfaceColor: "#eae7e3",
      borderColor: "#d1ccc6",
      mutedColor: "#8c8680",
      headingFont: "Crimson Text",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "2px",
    },
  },
  {
    name: "Forest Sanctuary",
    description: "Deep woodland greens on cream, dignified and grounded",
    settings: {
      primaryColor: "#2d5016",
      secondaryColor: "#4a7c2f",
      backgroundColor: "#f5f7f0",
      textColor: "#1a2410",
      accentColor: "#3d6b1f",
      surfaceColor: "#eaefe3",
      borderColor: "#c4d4b0",
      mutedColor: "#6b8055",
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
  {
    name: "Emerald Scripture",
    description: "Rich emerald and gold tones evoking illuminated manuscripts",
    settings: {
      primaryColor: "#1a4a2e",
      secondaryColor: "#b5924c",
      backgroundColor: "#f8f6ef",
      textColor: "#1c2818",
      accentColor: "#c9a84c",
      surfaceColor: "#eeebdf",
      borderColor: "#ccc9b8",
      mutedColor: "#7a8a6e",
      headingFont: "Crimson Text",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
  {
    name: "Olive & Ivory",
    description: "Muted sage and warm ivory, restful and contemplative",
    settings: {
      primaryColor: "#4a5e30",
      secondaryColor: "#7a8f5a",
      backgroundColor: "#faf9f4",
      textColor: "#252c1a",
      accentColor: "#5c7040",
      surfaceColor: "#f0eeea",
      borderColor: "#cdd4bb",
      mutedColor: "#7a8468",
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
  {
    name: "Dark Nave",
    description: "Night-mode cathedral greens — solemn, deep, and reverent",
    settings: {
      primaryColor: "#7ab648",
      secondaryColor: "#4a7c2f",
      backgroundColor: "#141a10",
      textColor: "#e0ead4",
      accentColor: "#a0c870",
      surfaceColor: "#1e2718",
      borderColor: "#2e3d22",
      mutedColor: "#6a8058",
      headingFont: "Playfair Display",
      bodyFont: "Lora",
      baseFontSize: 16,
      borderRadius: "4px",
    },
  },
];
